apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql
  labels:
    app: db-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-mysql
  template:
    metadata:
      labels:
        app: db-mysql
    spec:
      nodeName: cnp-node-w-1vmd
      containers:
      - name: db-mysql
        image: mysql:8.0.31
        ports:
        - containerPort: 3306
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: mysql-pvc
