apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-front
spec:
  selector:
    matchLabels:
      app: test-front
  replicas: 1
  template:
    metadata:
      labels:
        app: test-front
    spec:
      containers:
      - name: test-front
        image: uh2959/cucumber-front:17
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
